# Generated by Django 5.2.1 on 2025-06-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('original_text', models.TextField(blank=True)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('missing_info', models.JSONField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_uploads/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INCOMPLETE', 'Incomplete'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment')], default='SALE', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
