# Generated by Django 5.2.1 on 2025-06-20 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='original_sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicebook.voicerecording'),
        ),
    ]
